# Generated by Django 4.1.5 on 2023-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_service', '0003_cart_bookset'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
