# Generated by Django 4.1.5 on 2023-01-03 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.TextField(max_length=255)),
                ('surname', models.TextField(max_length=255)),
                ('phone_number', models.TextField(max_length=12, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
