# Generated by Django 4.1.5 on 2023-01-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
