# Generated by Django 4.1.5 on 2023-01-06 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30, unique=True)),
                ('surname', models.TextField(max_length=30, unique=True)),
            ],
        ),
    ]
